apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggdeeq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggdeeq
  template:
    metadata:
      labels:
        app: ggdeeq
    spec:
      containers:
      - image: okteto.dev/ggdeeq:latest
        name: ggdeeq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a26e57cb-0381-40cf-9a70-c5a6a02f6ec6"
        - name: Vless_Path
          value: "/vldste46dsh2"
        - name: Vmess_UUID
          value: "a26e57cb-0381-40cf-9a70-c5a6a02f6ec6"
        - name: Vmess_Path
          value: "/vmfwr32qwauj"
        - name: Share_Path
          value: "/v2link"
