apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaqqss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaqqss
  template:
    metadata:
      labels:
        app: aaqqss
    spec:
      containers:
      - image: okteto.dev/aaqqss:latest
        name: aaqqss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e7952a29-7b16-4908-aaa8-8eface9c4f26"
        - name: Vless_Path
          value: "/vldste46dsh2"
        - name: Vmess_UUID
          value: "e7952a29-7b16-4908-aaa8-8eface9c4f26"
        - name: Vmess_Path
          value: "/vmfwr32qwauj"
        - name: Share_Path
          value: "/v2link"
